DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS PERSON_SEX;
DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

--   phone and email list VARCHAR NOT NULL

CREATE SEQUENCE GLOBAL_SEQ START 100000;

CREATE TABLE USERS
(
--   person
  id         INTEGER PRIMARY KEY DEFAULT nextval('GLOBAL_SEQ'),
  first_name VARCHAR,
  last_name  VARCHAR,
  registered TIMESTAMP DEFAULT now(),
  enabled    BOOL DEFAULT TRUE,
  photo      BYTEA,
--   user
  password   VARCHAR NOT NULL
);
-- CREATE UNIQUE INDEX unique_email ON USERS (email);

CREATE TABLE USER_ROLES
(
  user_id INTEGER NOT NULL,
  role    VARCHAR,
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
